### ISSUE TITLE
Regression in 2.3.7. sort_only: true creates corrupt subquery

### ISSUE THREAD

**Issue by furedal** [Casecommons/pg_search#560]
I noticed that updating from `2.3.6` to `2.3.7` breaks queries using `sort_only: true` by adding a subquery with a WHERE clause with no condition.

See my example:

```
    pg_search_scope :sort_by_address,
                    ->(query, options = nil) {
                      search_options = {
                        query:     query,
                        against:   [:address],
                        using:     {
                          tsearch: {
                            prefix:     true,
                            any_word:   true,
                            sort_only:  true,
                            dictionary: 'simple'
                          }
                        },
                        ignoring:  :accents,
                        ranked_by: ':tsearch'
                      }
                      search_options = search_options.merge(options) if options.is_a?(Hash)
                      search_options
                    }

...
Item.sort_by_address('foo', order_within_rank: 'items.address')
```

This produces:
```
SELECT
	"items"."id"
FROM
	"items"
	INNER JOIN (
		SELECT
			"items"."id" AS pg_search_id,
			(ts_rank((to_tsvector('simple', f_unaccent (coalesce(("items"."address")::text, '')))), (to_tsquery('simple', ''' ' || f_unaccent ('foo') || ' ''' || ':*')), 0)) AS RANK
		FROM
			"items"
		WHERE
	) AS pg_search_3ae62594b1830faf2c5da4 ON "items"."id" = pg_search_3ae62594b1830faf2c5da4.pg_search_id
ORDER BY
	pg_search_3ae62594b1830faf2c5da4.rank DESC,
	items.address
```

Where the corrupted part is this part:
```
		FROM
			"items"
		WHERE
	)
```

**Comment by nertzy** [comment]
Thanks for reporting this. I verified that this no longer reproduces in pg_search 2.3.8 across the supported Active Record 7.2, 8.0, and 8.1 versions.

In 2.3.8, the internal rank join was changed to use an Arel join. With that implementation, Arel omits the empty predicate when every search feature has `sort_only: true`, so the generated subquery no longer contains a bare `WHERE` clause.

Upgrading to 2.3.8 should resolve the issue.

**Comment by jpcody** [comment]
We're still experiencing this in 2.3.8. We have a scope defined as:

```rb
pg_search_scope :full_text_sort,
  against: { cas_number: "A", name: "B" },
  using: { tsearch: { normalization: 2, prefix: true, sort_only: true } }
```

This ends up generating a bare `WHERE` clause. It appears `conditions` rejects every feature that is sort-only [here](https://github.com/Casecommons/pg_search/blob/v2.3.8/lib/pg_search/scope_options.rb#L93-L100). And since that's the only feature in use, that gets converted into an empty where clause.

We're currently testing the following monkeypatch locally:

```rb
module PgSearchSortOnlyConditionsFix
  private

  def conditions
    condition = super

    return if condition.is_a?(Arel::Nodes::Or) && condition.children.empty?

    condition
  end
end

PgSearch::ScopeOptions.prepend(PgSearchSortOnlyConditionsFix)
```

I just wanted to leave a note here in case others run into this.

**Comment by furedal** [comment]
@nertzy

Its still broken on **2.4.0**.

I rechecked with the same `sort_only: true`-only scope pattern from the original report. Generated SQL still has a bare `WHERE` in the rank subquery:

```sql
FROM "bid_items" WHERE )
```

That fails at runtime with:

```
PG::SyntaxError: ERROR:  syntax error at or near ")"
```

Looking at `PgSearch::ScopeOptions` in 2.4.0, `conditions` still rejects every `sort_only` feature and then does:

```ruby
Arel::Nodes::Or.new(expressions)  # expressions is []
```

…and `subquery` still calls `.where(conditions)`. When every feature is `sort_only`, that empty OR lands in the WHERE clause as invalid SQL.

So the 2.3.8 “Arel omits empty predicates” claim doesn’t hold for this path — at least not on 2.3.8 (see @jpcody’s comment) or 2.4.0. The monkeypatch from that comment still looks like the right local workaround until `conditions` returns `nil` (or otherwise skips `.where`) when there are no non-`sort_only` features.
